name = "batys-pest-control"
main = ".open-next/worker.js"
compatibility_date = "2026-07-14"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[routes]]
pattern = "batyspestcontrol.com/*"
zone_name = "batyspestcontrol.com"

[[routes]]
pattern = "www.batyspestcontrol.com/*"
zone_name = "batyspestcontrol.com"

[[routes]]
pattern = "*.batyspestcontrol.com/*"
zone_name = "batyspestcontrol.com"
