name = "batys-pest-control"
main = ".open-next/worker.js"
compatibility_date = "2026-07-14"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "batys-pest-control"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "batys-pest-control-opennext-cache"

[[routes]]
pattern = "batyspestcontrol.com/*"
zone_name = "batyspestcontrol.com"

[[routes]]
pattern = "www.batyspestcontrol.com/*"
zone_name = "batyspestcontrol.com"

[[routes]]
pattern = "*.batyspestcontrol.com/*"
zone_name = "batyspestcontrol.com"
