import Image from 'next/image';
import Link from 'next/link';
import { pestServices, states, stateUrl } from '@/lib/locations';
import { SITE } from '@/lib/site';

const cityCount = states.reduce((n,s)=>n+s.cities.length,0);
const featured = ['emergency-pest-control','termite-control','bed-bug-treatment','rodent-control','cockroach-control','mosquito-control'].map(slug=>pestServices.find(s=>s.slug===slug)).filter(Boolean);
const faqs = [
 ['How fast can a pest-control provider respond?','Response time depends on city, pest type, season, urgency, and provider capacity. Call to confirm current availability.'],
 ['Should I identify the pest before calling?','Photographs, droppings, damage, sounds, odors, nesting material, and the time activity occurs are useful, but a provider should confirm identification during inspection.'],
 ['Are providers licensed and insured?','Requirements vary by state. Confirm the specific company’s current license, insurance, treatment scope, products, and written estimate before authorizing work.'],
 ['What should be included in a quote?','Ask for inspection findings, target pest, treatment areas, products or methods, preparation, visits, exclusions, warranty, follow-up, and total price.'],
 ['Is one treatment always enough?','No. Colonies, eggs, hidden harborages, structural entry points, seasonal pressure, and sanitation or moisture conditions can require monitoring or repeat service.'],
 ['How do I protect children and pets?','Tell the provider about children, pets, allergies, aquariums, food areas, and sensitive occupants. Follow written preparation and re-entry instructions exactly.'],
];

export default function HomePage(){return <>
 <section className="relative isolate overflow-hidden bg-[#092e27] text-white"><Image src="/images/pest-control-hero.webp" alt="Pest-control technician inspecting a property" fill priority unoptimized className="object-cover object-center opacity-35" sizes="100vw"/><div className="absolute inset-0 bg-gradient-to-r from-[#071f1b] via-[#092e27]/95 to-[#092e27]/45"/><div className="relative mx-auto grid min-h-[620px] max-w-7xl items-center gap-10 px-4 py-16 lg:grid-cols-[1.15fr_.85fr]"><div><p className="inline-flex rounded-full bg-emerald-500/15 px-4 py-2 text-xs font-black uppercase tracking-[.18em] text-emerald-200">24/7 Pest-Control Availability Line</p><h1 className="mt-6 max-w-3xl font-heading text-5xl font-black leading-[1.03] sm:text-6xl">Pest Control & Extermination Services Near You</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-emerald-50/85">Research the problem, compare service options, and check availability with independent local pest-control providers across the United States.</p><div className="mt-7 flex flex-wrap gap-4"><a href={SITE.phoneHref} className="rounded-lg bg-emerald-500 px-6 py-4 font-black">Call {SITE.phoneDisplay}</a><Link href="/services" className="rounded-lg border border-white/25 bg-white/10 px-6 py-4 font-black">Get Service Information</Link></div><div className="mt-7 flex flex-wrap gap-5 text-sm font-bold text-emerald-50/90">{['Independent providers','Nationwide location routes','Inspection-first guidance'].map(x=><span key={x}>✓ {x}</span>)}</div></div><aside className="rounded-xl bg-white p-7 text-[#10233b] shadow-2xl"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Request fast service</p><h2 className="mt-2 font-heading text-2xl font-black">Tell us what is going on</h2><div className="mt-5 grid gap-3">{['Full name','Phone number','City or ZIP code','Pest or service needed'].map(x=><div key={x} className="rounded-md border border-slate-200 px-4 py-3 text-sm text-slate-400">{x}</div>)}</div><a href={SITE.phoneHref} className="mt-4 block rounded-md bg-emerald-500 px-5 py-4 text-center font-black text-white">Call for Availability</a><p className="mt-3 text-center text-xs text-slate-500">Provider coverage and response time vary by location.</p></aside></div></section>

 <section className="border-b border-slate-200 bg-white px-4"><div className="mx-auto grid max-w-7xl grid-cols-2 lg:grid-cols-4">{[[51,'States & DC'],[`${cityCount.toLocaleString()}+`,'Location routes'],[pestServices.length,'Service topics'],['24/7','Phone access']].map(([v,l],i)=><div key={l} className={`p-6 text-center ${i?'border-l':''}`}><strong className="font-heading text-3xl font-black text-[#10233b]">{v}</strong><p className="mt-1 text-xs font-bold uppercase tracking-wider text-slate-500">{l}</p></div>)}</div></section>

 <section className="bg-slate-50 px-4 py-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Our services</p><h2 className="mt-3 max-w-3xl font-heading text-4xl font-black text-[#10233b]">Complete pest-control service information</h2><p className="mt-4 max-w-3xl leading-7 text-slate-600">Start with the pest or service intent, then choose your state and city for locally organized information.</p><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{featured.map((s,i)=>s&&<Link key={s.slug} href={`/services/${s.slug}`} className="rounded-xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><span className="grid h-10 w-10 place-items-center rounded-lg bg-emerald-100 font-black text-emerald-800">0{i+1}</span><h3 className="mt-5 font-heading text-xl font-black text-[#10233b]">{s.name}</h3><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{s.description}</p><span className="mt-5 inline-flex text-sm font-black text-emerald-700">Learn more →</span></Link>)}</div><Link href="/services" className="mt-8 inline-flex rounded-lg bg-[#10233b] px-6 py-4 font-black text-white">View all services</Link></div></section>

 <section className="px-4 py-20"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-2"><div className="relative min-h-[420px] overflow-hidden rounded-2xl bg-slate-200"><Image src="/images/pest-control-hero.webp" alt="Pest inspection and treatment planning" fill unoptimized className="object-cover" sizes="(min-width:1024px) 50vw,100vw"/></div><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Why choose Batys</p><h2 className="mt-3 font-heading text-4xl font-black text-[#10233b]">A pest-control research platform you can actually understand</h2><p className="mt-5 leading-8 text-slate-600">Batys is not presented as a single licensed applicator in every city. It organizes service information and location routes, then helps users check availability with independent providers.</p><div className="mt-8 grid gap-5 sm:grid-cols-2">{[['Location-first navigation','State and city pages preserve geographic context.'],['Clear provider disclosure','No invented office, technician, or license claims.'],['Service-specific guidance','Inspection, treatment, preparation, and prevention topics.'],['Hiring safeguards','Verify credentials, scope, products, price, and follow-up.'],['Residential and commercial','Coverage across common property types and pest entities.'],['Strong internal linking','Services, cities, states, and guides connect logically.']].map(([h,p])=><div key={h} className="flex gap-3"><span className="text-emerald-600">✓</span><div><h3 className="font-black text-[#10233b]">{h}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{p}</p></div></div>)}</div></div></div></section>

 <section className="border-y border-slate-200 bg-slate-50 px-4 py-10"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-x-12 gap-y-5 text-sm font-black text-slate-500">{['Termites','Bed Bugs','Rodents','Cockroaches','Ants','Mosquitoes','Spiders'].map(x=><span key={x}>{x}</span>)}</div></section>

 <section className="px-4 py-20"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.05fr_.95fr]"><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">About us</p><h2 className="mt-3 font-heading text-4xl font-black text-[#10233b]">Nationwide pest information built around local intent</h2><p className="mt-5 leading-8 text-slate-600">The site connects pest entities, service intent, state, city, inspection questions, treatment options, and prevention guidance. That structure is designed to help users make a better-informed service call.</p><p className="mt-4 leading-8 text-slate-600">Independent providers remain responsible for confirming coverage, licensing, findings, recommendations, contracts, products, warranties, and work performed.</p><div className="mt-7 flex gap-3"><Link href="/about" className="rounded-lg bg-[#10233b] px-6 py-4 font-black text-white">More About Us</Link><a href={SITE.phoneHref} className="rounded-lg border border-slate-300 px-6 py-4 font-black text-[#10233b]">Call {SITE.phoneDisplay}</a></div></div><div className="grid grid-cols-2 gap-4"><div className="min-h-[340px] rounded-2xl bg-emerald-900 p-7 text-white"><p className="text-sm font-bold text-emerald-200">Coverage</p><strong className="mt-5 block font-heading text-5xl font-black">50</strong><p className="mt-2">states plus Washington, DC</p></div><div className="mt-12 min-h-[340px] rounded-2xl bg-slate-100 p-7"><p className="text-sm font-bold text-emerald-700">Service topics</p><strong className="mt-5 block font-heading text-5xl font-black text-[#10233b]">70+</strong><p className="mt-2 text-slate-600">inspection, treatment, removal, and prevention intents</p></div></div></div></section>

 <section className="bg-[#0b263e] px-4 py-20 text-white"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-300">How it works</p><h2 className="mt-3 font-heading text-4xl font-black">Pest-control help in four simple steps</h2><div className="mt-10 grid gap-8 md:grid-cols-4">{[['Choose the problem','Start with the pest, damage, inspection need, or property type.'],['Select your location','Choose a state and city to keep local context clear.'],['Review the guidance','Understand signs, methods, preparation, and hiring questions.'],['Check availability','Call and verify provider coverage, credentials, scope, and price.']].map(([h,p],i)=><div key={h}><span className="text-5xl font-black text-white/15">0{i+1}</span><h3 className="mt-3 text-xl font-black">{h}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{p}</p></div>)}</div></div></section>

 <section className="px-4 py-20"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1fr_.9fr]"><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Service areas</p><h2 className="mt-3 font-heading text-4xl font-black text-[#10233b]">Proudly organizing pest services across the United States</h2><p className="mt-5 leading-8 text-slate-600">Select a state to browse city-specific pest-control routes and service topics.</p><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3">{states.slice(0,18).map(s=><Link key={s.code} href={stateUrl(s)} className="rounded-lg border border-slate-200 px-4 py-3 text-sm font-bold text-slate-700 hover:border-emerald-500 hover:text-emerald-700">{s.name}</Link>)}</div><Link href="/locations" className="mt-7 inline-flex rounded-lg bg-[#10233b] px-6 py-4 font-black text-white">See all service areas</Link></div><div className="rounded-2xl bg-slate-100 p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Nationwide structure</p><div className="mt-5 rounded-xl bg-white p-7 shadow-sm"><strong className="font-heading text-5xl font-black text-[#10233b]">{cityCount.toLocaleString()}+</strong><p className="mt-2 font-bold text-slate-600">city and community routes</p><div className="mt-7 space-y-3 text-sm text-slate-600"><p>✓ State-level service discovery</p><p>✓ City-specific service links</p><p>✓ Service-to-location internal linking</p><p>✓ Independent-provider disclosures</p></div></div></div></div></section>

 <section className="bg-slate-50 px-4 py-20"><div className="mx-auto max-w-4xl text-center"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">FAQ</p><h2 className="mt-3 font-heading text-4xl font-black text-[#10233b]">Pest-control questions, answered</h2><div className="mt-10 space-y-3 text-left">{faqs.map(([q,a])=><details key={q} className="rounded-xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer font-black text-[#10233b]">{q}</summary><p className="mt-3 leading-7 text-slate-600">{a}</p></details>)}</div></div></section>

 <section className="bg-emerald-500 px-4 py-14 text-white"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 md:flex-row md:items-center"><div><h2 className="font-heading text-3xl font-black">Pest problem? Start with the right service.</h2><p className="mt-2 text-emerald-50">Browse the site or call to check local provider availability.</p></div><div className="flex gap-3"><a href={SITE.phoneHref} className="rounded-lg bg-[#10233b] px-6 py-4 font-black">Call {SITE.phoneDisplay}</a><Link href="/services" className="rounded-lg bg-white px-6 py-4 font-black text-[#10233b]">View Services</Link></div></div></section>
 </>}
