import type { Metadata } from 'next';
import { PolicyPage } from '@/components/PolicyPage';

export const metadata: Metadata = { title: 'Terms & Conditions', description: 'Terms and conditions for using Batys Pest Control information, location pages, referrals, and service-request features.', alternates: { canonical: '/terms' } };

export default function TermsPage() {
  return <PolicyPage eyebrow="Legal Terms" title="Terms & Conditions" description="These terms govern access to and use of Batys Pest Control, including its information, location directories, referral features, and communications." lastUpdated="July 22, 2026" sections={[
    { heading: 'Acceptance of these terms', paragraphs: ['By accessing or using this website, you agree to these terms and the Privacy Policy. If you do not agree, do not use the website or submit a service request.'] },
    { heading: 'Information and referral platform', paragraphs: ['Batys provides general pest-control information, location-based service pages, and referral or availability-routing features. Batys is not represented as the licensed pest-control operator performing every service in every location. Independent providers determine whether they accept a request and remain responsible for inspection, diagnosis, recommendations, products, pricing, contracts, warranties, permits, licensing, insurance, and work performed.'] },
    { heading: 'No guaranteed availability or results', paragraphs: ['Provider availability, response time, price, treatment method, number of visits, warranty, and results are not guaranteed by the website. Pest biology, property conditions, access, neighboring activity, weather, sanitation, moisture, repairs, and user compliance can affect outcomes.'] },
    { heading: 'User responsibilities', bullets: ['Provide accurate contact, location, and pest-problem information','Verify the provider’s identity, licensing, insurance, written scope, price, products, preparation, and warranty','Follow product labels, written safety instructions, re-entry times, and applicable laws','Use emergency, medical, veterinary, poison-control, or public-safety services when the situation requires them','Do not misuse the website, submit fraudulent requests, interfere with security, or copy content unlawfully'] },
    { heading: 'Third-party providers and links', paragraphs: ['Independent providers and third-party websites have their own terms, privacy practices, and service obligations. Batys is not responsible for a provider’s acts, omissions, representations, contracts, or work, except where applicable law requires otherwise.'] },
    { heading: 'Intellectual property', paragraphs: ['Website design, original text, graphics, data organization, branding, and software are protected by applicable intellectual-property laws. Limited personal, noncommercial use is permitted. Automated extraction, republication, resale, or creation of misleading copies is prohibited without written permission.'] },
    { heading: 'Limitation and governing principles', paragraphs: ['To the fullest extent permitted by law, the website and information are provided without warranties of uninterrupted access, completeness, or fitness for a particular purpose. Nothing in these terms excludes rights or liabilities that cannot legally be excluded. Any dispute should first be raised through the contact page so the issue can be reviewed.'] },
    { heading: 'Changes to these terms', paragraphs: ['These terms may be revised as website features, business practices, or legal requirements change. Continued use after an update means the revised terms apply from the stated effective date.'] },
  ]} />;
}
