export type Article = {
  slug: string; title: string; category: string; pest: string; serviceSlug: string;
  summary: string; signs: string[]; causes: string[]; methods: string[]; prevention: string[];
};

export const articles: Article[] = [
 {slug:'early-signs-of-termite-activity',title:'Early Signs of Termite Activity Homeowners Should Not Ignore',category:'Termites',pest:'termites',serviceSlug:'termite-control',summary:'Learn how mud tubes, discarded wings, hollow wood, frass, moisture, and structural changes can indicate termite activity.',signs:['mud tubes on foundations or walls','discarded swarm wings near windows and doors','wood that sounds hollow when tapped','blistered paint or damaged trim','termite droppings or frass'],causes:['soil-to-wood contact','persistent moisture and plumbing leaks','untreated structural lumber','foundation cracks and utility penetrations'],methods:['detailed structural inspection','soil or localized termiticide treatment','bait-station monitoring','wood treatment and moisture correction'],prevention:['repair leaks and drainage problems','keep wood away from soil','maintain inspection access','schedule periodic termite inspections']},
 {slug:'termite-treatment-options-explained',title:'Termite Treatment Options Explained: Liquid Barriers, Baits, and Wood Treatments',category:'Termites',pest:'termites',serviceSlug:'termite-treatment',summary:'Compare common termite treatment methods and understand how inspection findings determine the correct approach.',signs:['active mud tubes','swarmers or wings','damaged structural wood','live termites in galleries'],causes:['subterranean colonies','drywood infestations','moisture-damaged timber','unsealed structural access'],methods:['liquid soil barriers','termite bait systems','localized foam or injection','borate wood treatment'],prevention:['correct moisture','remove cellulose debris','maintain treatment zones','monitor bait stations']},
 {slug:'how-to-prepare-for-bed-bug-inspection',title:'How to Prepare for a Bed Bug Inspection Without Spreading the Infestation',category:'Bed Bugs',pest:'bed bugs',serviceSlug:'bed-bug-inspection',summary:'Prepare bedrooms, furniture, clothing, and records for inspection while avoiding actions that can spread bed bugs.',signs:['dark fecal spotting','cast skins','live bugs in seams','clusters of unexplained bites','blood marks on bedding'],causes:['travel and luggage','used furniture','movement between apartments','uncontrolled clutter'],methods:['visual inspection','mattress and furniture examination','interceptor monitoring','canine inspection where appropriate'],prevention:['inspect luggage','use encasements','reduce hiding places','avoid moving infested items']},
 {slug:'bed-bug-heat-treatment-guide',title:'Bed Bug Heat Treatment: Process, Preparation, Limitations, and Follow-Up',category:'Bed Bugs',pest:'bed bugs',serviceSlug:'bed-bug-heat-treatment',summary:'Understand professional heat treatment, temperature monitoring, preparation, risks, and post-treatment verification.',signs:['confirmed bed bugs','activity in multiple rooms','eggs and nymphs in furniture','repeated bites after DIY treatment'],causes:['hidden harborages','incomplete pesticide coverage','movement of infested belongings','adjacent-unit activity'],methods:['whole-room heat','temperature sensor monitoring','targeted residual treatment','follow-up inspection'],prevention:['follow preparation instructions','do not remove untreated items','use interceptors','report renewed activity quickly']},
 {slug:'mouse-entry-points-homeowners-miss',title:'Mouse Entry Points Homeowners Commonly Miss',category:'Rodents',pest:'mice',serviceSlug:'mouse-control',summary:'Find common gaps around foundations, roofs, garages, utilities, doors, and crawl spaces that allow mice indoors.',signs:['small droppings','gnaw marks','nighttime scratching','greasy rub marks','shredded nesting material'],causes:['gaps around pipes','damaged door sweeps','open garage corners','roofline and vent openings'],methods:['interior and exterior inspection','trapping and monitoring','rodent exclusion','sanitation correction'],prevention:['seal quarter-inch gaps','repair screens and sweeps','store food securely','reduce exterior shelter']},
 {slug:'rat-infestation-warning-signs',title:'Rat Infestation Warning Signs, Health Risks, and Inspection Priorities',category:'Rodents',pest:'rats',serviceSlug:'rat-control',summary:'Recognize rat droppings, burrows, tracks, gnawing, odors, noises, and contamination before damage escalates.',signs:['large spindle-shaped droppings','burrows near structures','gnawed wiring or containers','musky odors','footprints and tail marks'],causes:['accessible waste','standing water','sewer or drain access','dense vegetation and clutter'],methods:['species identification','trap placement','burrow and sewer assessment','structural exclusion'],prevention:['secure waste','eliminate water sources','trim vegetation','seal structural gaps']},
 {slug:'cockroach-infestation-signs',title:'Cockroach Infestation Signs and Why Daytime Sightings Matter',category:'Cockroaches',pest:'cockroaches',serviceSlug:'cockroach-control',summary:'Understand droppings, egg cases, odors, harborages, and daytime activity associated with cockroach infestations.',signs:['pepper-like droppings','egg cases','musty odor','live roaches at night or daytime','smear marks near moisture'],causes:['food residue','water leaks','warm appliance voids','shared walls and deliveries'],methods:['species identification','gel baiting','insect growth regulators','crack-and-crevice treatment'],prevention:['clean food residue','repair leaks','seal gaps','inspect packages and appliances']},
 {slug:'german-cockroach-treatment-plan',title:'German Cockroach Treatment Plan: Inspection, Baiting, Sanitation, and Follow-Up',category:'Cockroaches',pest:'German cockroaches',serviceSlug:'german-cockroach-treatment',summary:'Learn why German cockroach control requires detailed inspection, bait placement, sanitation, and repeat monitoring.',signs:['small tan roaches with dark stripes','droppings in cabinets','egg cases near appliances','activity around sinks and refrigerators'],causes:['rapid indoor reproduction','food and grease residue','warm humid voids','movement in boxes or appliances'],methods:['gel bait rotation','growth regulators','vacuuming harborages','targeted dust or residual products'],prevention:['remove competing food','repair moisture','declutter cabinets','monitor with sticky traps']},
 {slug:'carpenter-ant-damage-vs-termites',title:'Carpenter Ant Damage vs. Termite Damage: Key Differences',category:'Ants',pest:'carpenter ants',serviceSlug:'carpenter-ant-control',summary:'Compare galleries, frass, mud tubes, swarmers, moisture damage, and nesting behavior to distinguish carpenter ants from termites.',signs:['coarse sawdust-like frass','smooth wood galleries','large ants indoors','rustling in wall voids','winged ants'],causes:['moist or decayed wood','roof and plumbing leaks','tree limbs contacting structures','satellite nests indoors'],methods:['nest-location inspection','moisture assessment','targeted bait or treatment','damaged wood repair'],prevention:['repair leaks','replace decayed wood','trim branches','seal exterior gaps']},
 {slug:'ant-infestation-source-control',title:'Ant Infestation Source Control: Why Killing Visible Ants Is Not Enough',category:'Ants',pest:'ants',serviceSlug:'ant-control',summary:'Understand trails, colony structure, nesting sites, food sources, moisture, baiting, and exclusion for lasting ant control.',signs:['persistent trails','ants around food or sinks','soil mounds','activity from wall gaps','winged reproductives'],causes:['accessible sugar or protein','moisture','exterior nests','structural entry points'],methods:['species identification','bait selection','nest treatment','exterior perimeter correction'],prevention:['seal food','clean trails','repair leaks','trim vegetation']},
 {slug:'mosquito-breeding-sites-yard',title:'Mosquito Breeding Sites Hidden Around the Yard',category:'Mosquitoes',pest:'mosquitoes',serviceSlug:'mosquito-control',summary:'Identify containers, gutters, drains, tarps, toys, vegetation, and drainage areas that support mosquito breeding.',signs:['heavy biting near shade','larvae in standing water','activity after rain','mosquitoes around patios'],causes:['water-filled containers','blocked gutters','poor drainage','dense shaded vegetation'],methods:['source inspection','larval control','targeted barrier treatment','habitat modification'],prevention:['empty standing water','clean gutters','improve drainage','trim dense vegetation']},
 {slug:'flea-infestation-home-pets',title:'Flea Infestation in Homes With Pets: Life Cycle and Treatment Priorities',category:'Fleas & Ticks',pest:'fleas',serviceSlug:'flea-control',summary:'Learn how flea eggs, larvae, pupae, pets, carpets, furniture, and outdoor areas affect treatment success.',signs:['pets scratching','small jumping insects','flea dirt','bites around ankles','activity in pet resting areas'],causes:['untreated pets','wildlife hosts','carpet and furniture development','outdoor shaded habitat'],methods:['veterinary coordination','vacuuming and laundering','growth regulator treatment','follow-up for emerging adults'],prevention:['maintain pet prevention','wash bedding','vacuum regularly','limit wildlife access']},
 {slug:'tick-control-property-guide',title:'Residential Tick Control: Property Inspection and Habitat Reduction Guide',category:'Fleas & Ticks',pest:'ticks',serviceSlug:'tick-control',summary:'Reduce tick exposure by inspecting vegetation, wildlife pathways, leaf litter, edges, pets, and outdoor activity areas.',signs:['ticks on people or pets','activity near wooded edges','wildlife movement','dense leaf litter'],causes:['deer and rodent hosts','humid vegetation','unmanaged property edges','pet exposure'],methods:['habitat assessment','targeted perimeter treatment','rodent-host management','pet protection coordination'],prevention:['remove leaf litter','create dry borders','trim vegetation','use veterinarian-approved prevention']},
 {slug:'spider-control-home-guide',title:'Spider Control in and Around the Home: Web Removal, Prey Reduction, and Exclusion',category:'Spiders',pest:'spiders',serviceSlug:'spider-control',summary:'Understand why lasting spider control depends on species identification, prey reduction, web removal, lighting, and sealing.',signs:['repeated web building','egg sacs','spiders in basements or garages','activity near exterior lights'],causes:['abundant insect prey','cluttered harborages','gaps around doors and vents','exterior lighting'],methods:['species assessment','web and egg-sac removal','targeted crack treatment','insect-prey reduction'],prevention:['seal gaps','reduce clutter','adjust lighting','repair screens']},
 {slug:'wasp-nest-removal-safety',title:'Wasp Nest Removal Safety: When Not to Attempt DIY Removal',category:'Stinging Insects',pest:'wasps',serviceSlug:'wasp-nest-removal',summary:'Learn how nest location, species, colony size, allergies, ladders, wall voids, and defensive behavior affect removal risk.',signs:['repeated flight to one opening','visible paper nest','aggressive guarding','buzzing inside walls'],causes:['protected eaves and voids','food and water sources','open structural gaps','seasonal colony growth'],methods:['species and nest assessment','protective removal','void treatment','entry-point repair after inactivity'],prevention:['seal gaps off-season','manage food waste','inspect eaves','avoid disturbing active nests']},
 {slug:'bee-removal-vs-extermination',title:'Bee Removal vs. Extermination: Colonies, Swarms, and Structural Hives',category:'Stinging Insects',pest:'bees',serviceSlug:'bee-removal',summary:'Understand the difference between temporary swarms, established hives, live removal, comb removal, and structural repair.',signs:['clustered swarm','steady traffic into a wall','honey or staining','buzzing in structural voids'],causes:['available cavities','unsealed vents','previous comb odor','seasonal swarming'],methods:['species confirmation','live removal where feasible','comb and honey removal','entry repair'],prevention:['seal cavities','screen vents','remove old comb','inspect recurring entry points']},
 {slug:'pantry-pest-identification',title:'Pantry Pest Identification and Food-Storage Cleanup',category:'Stored Product Pests',pest:'pantry pests',serviceSlug:'pantry-pest-control',summary:'Identify beetles, moths, larvae, webbing, damaged packaging, and infested dry goods before treatment.',signs:['small beetles in cupboards','moths near food storage','webbing in packages','larvae or holes in dry goods'],causes:['infested products','open packaging','spilled grain or pet food','long-term storage'],methods:['product-by-product inspection','disposal or controlled treatment','vacuuming cracks','monitoring traps'],prevention:['use sealed containers','rotate stock','clean spills','inspect purchases']},
 {slug:'carpet-beetle-damage-guide',title:'Carpet Beetle Damage: Larvae, Shed Skins, Fabrics, and Hidden Food Sources',category:'Fabric Pests',pest:'carpet beetles',serviceSlug:'carpet-beetle-control',summary:'Find carpet beetle larvae, shed skins, fabric damage, lint, pet hair, dead insects, and hidden breeding sources.',signs:['irregular fabric holes','hairy larvae','shed skins','adult beetles near windows'],causes:['natural-fiber materials','lint and pet hair','dead insects in voids','stored textiles'],methods:['source inspection','detailed vacuuming','laundering or dry cleaning','targeted crack treatment'],prevention:['store textiles sealed','clean lint zones','inspect natural fibers','remove insect debris']},
 {slug:'wildlife-entry-attic-guide',title:'Wildlife in the Attic: Entry Signs, Damage, and Humane Exclusion Planning',category:'Wildlife',pest:'nuisance wildlife',serviceSlug:'wildlife-removal',summary:'Assess noises, droppings, nesting material, roof damage, vents, soffits, and timing before wildlife exclusion.',signs:['heavy nighttime movement','large droppings','torn vents or soffits','nesting material','strong animal odor'],causes:['damaged roof edges','open vents','tree access','available den sites'],methods:['species identification','entry inspection','one-way exclusion where lawful','cleanup and repair'],prevention:['repair roof openings','screen vents','trim access branches','secure waste']},
 {slug:'raccoon-removal-property',title:'Raccoon Removal From Attics and Crawl Spaces: Inspection and Exclusion',category:'Wildlife',pest:'raccoons',serviceSlug:'raccoon-removal',summary:'Understand raccoon entry, denning, young, contamination, structural damage, exclusion timing, and repair.',signs:['heavy footsteps at night','large latrine areas','damaged soffits','tracks and tipped waste'],causes:['roof access','unsecured trash','open crawl spaces','protected den cavities'],methods:['occupancy assessment','lawful removal or exclusion','latrine cleanup','structural repair'],prevention:['secure containers','repair soffits','cap access points','trim branches']},
 {slug:'pest-inspection-checklist',title:'Professional Pest Inspection Checklist for Homeowners and Property Managers',category:'Inspection',pest:'common structural pests',serviceSlug:'pest-inspection',summary:'Use a structured checklist covering pest evidence, moisture, sanitation, entry points, harborages, damage, and documentation.',signs:['droppings or frass','live or dead pests','nests and webs','damage or contamination','tracks, odors, and noises'],causes:['moisture','food and waste','structural gaps','clutter and vegetation'],methods:['interior inspection','exterior inspection','moisture and entry assessment','written findings and recommendations'],prevention:['schedule routine checks','document changes','correct conducive conditions','maintain exclusion']},
 {slug:'questions-before-pest-treatment',title:'Questions to Ask Before Approving a Pest-Control Treatment',category:'Hiring Guide',pest:'household pests',serviceSlug:'general-pest-control',summary:'Ask better questions about identification, products, methods, licensing, preparation, price, warranty, and follow-up.',signs:['unclear pest identification','vague treatment scope','pressure to sign immediately','missing product or price details'],causes:['incomplete inspection','generic sales scripts','unwritten exclusions','misunderstood expectations'],methods:['request written findings','verify credentials','compare scopes','review labels and instructions'],prevention:['keep records','avoid verbal-only promises','confirm warranty limits','document follow-up']},
 {slug:'integrated-pest-management-home',title:'Integrated Pest Management for Homes: Inspection, Prevention, Monitoring, and Targeted Treatment',category:'Prevention',pest:'household pests',serviceSlug:'general-pest-control',summary:'Learn how integrated pest management combines identification, thresholds, sanitation, exclusion, monitoring, and targeted products.',signs:['recurring seasonal pests','multiple conducive conditions','repeated broad treatments','activity returning after service'],causes:['unresolved entry points','food and moisture','poor monitoring','treatment without source correction'],methods:['accurate identification','conducive-condition correction','monitoring','least-disruptive targeted treatment'],prevention:['maintain sanitation','repair gaps and leaks','track pest activity','review results']},
 {slug:'commercial-pest-control-plan',title:'Commercial Pest-Control Plan: Documentation, Monitoring, Sanitation, and Corrective Action',category:'Commercial',pest:'commercial facility pests',serviceSlug:'commercial-pest-control',summary:'Build a commercial pest-management plan around risk zones, monitoring, sanitation, documentation, corrective actions, and audits.',signs:['pest sightings in production or storage','damaged goods','droppings near docks','audit findings','trend increases in monitors'],causes:['receiving activity','waste and food residue','door and dock gaps','storage congestion'],methods:['site risk assessment','device mapping','scheduled monitoring','documented corrective action'],prevention:['train staff','manage waste','inspect deliveries','close structural gaps']},
 {slug:'seasonal-pest-prevention-calendar',title:'Seasonal Pest Prevention Calendar for Property Owners',category:'Prevention',pest:'seasonal pests',serviceSlug:'preventative-pest-control',summary:'Plan spring, summer, fall, and winter inspections for insects, rodents, mosquitoes, stinging pests, and wildlife.',signs:['spring swarmers','summer mosquito pressure','fall rodent entry','winter indoor harborages'],causes:['temperature shifts','rain and moisture','breeding cycles','seasonal shelter seeking'],methods:['seasonal inspection','exterior maintenance','monitoring','targeted prevention'],prevention:['clean gutters','seal gaps before fall','manage standing water','inspect stored items']},
];

export function findArticle(slug:string){return articles.find(a=>a.slug===slug)}

export function articleSections(a:Article){
 const list=(items:string[])=>items.map(x=>x).join(', ');
 return [
  {heading:`Understanding ${a.pest} and the purpose of this guide`,paragraphs:[`${a.summary} The first priority is not choosing a pesticide or copying a treatment seen online. The first priority is establishing what pest is present, where activity is concentrated, how extensive the problem may be, and which conditions are supporting it. A reliable inspection separates confirmed evidence from assumptions and creates a defensible basis for treatment, exclusion, cleanup, monitoring, and prevention.`,`${a.pest} problems are rarely explained by a single visible insect, dropping, bite, noise, or damaged material. The useful evidence is the pattern: location, frequency, time of day, season, moisture, food access, structural openings, nesting material, travel history, neighboring activity, and previous control attempts. Record those details before disturbing the area because cleaning, spraying, moving furniture, sealing an active opening, or discarding items can remove evidence or spread activity.`]},
  {heading:`Common signs associated with ${a.pest}`,paragraphs:[`Important signs include ${list(a.signs)}. None of these signs should be interpreted in isolation. Similar evidence may be produced by another insect, rodent, wildlife species, moisture problem, fungal condition, or ordinary building wear. Photographs and dated notes help establish whether activity is increasing, moving, seasonal, or responding to corrective work.`,`Inspect both the immediate activity zone and the conditions around it. Look above, below, behind, and outside the affected area. Check plumbing penetrations, wall-floor junctions, utility lines, roof edges, crawl spaces, attics, storage zones, exterior vegetation, waste areas, drains, doors, windows, vents, and neighboring rooms. The source is frequently separated from the place where the pest was first noticed.`]},
  {heading:'Why the problem develops',paragraphs:[`Conditions commonly linked with this topic include ${list(a.causes)}. These factors do not prove an infestation, but they explain why a property may remain attractive or accessible. A treatment that ignores food, water, shelter, entry routes, host animals, damaged materials, or recurring deliveries may reduce visible activity without changing the underlying pressure.`,`Conducive conditions should be prioritized according to impact. Active leaks, sewage or drainage defects, food contamination, unsafe electrical damage, structural openings, and occupied nests require faster attention than cosmetic gaps or low-risk clutter. Some corrections can be completed immediately; others should wait until the provider confirms that sealing, demolition, cleaning, or item movement will not interfere with inspection or trap pests inside.`]},
  {heading:'What a professional inspection should cover',paragraphs:[`A professional inspection should document the target pest or the remaining identification uncertainty, active and inactive evidence, likely harborages or nesting sites, structural access, moisture, sanitation, damage, sensitive areas, and the practical limitations of inspection. Hidden wall voids, inaccessible crawl spaces, finished ceilings, stored inventory, neighboring units, and roof conditions may restrict certainty and should be identified in writing.`,`Ask the inspector to distinguish observations from conclusions. “Droppings found under the sink” is an observation. “An active mouse infestation is present” is a conclusion that should be supported by dropping size, freshness, tracks, gnawing, trap results, entry points, or other evidence. This distinction reduces misdiagnosis and helps compare proposals from different providers.`]},
  {heading:`Treatment and management options for ${a.pest}`,paragraphs:[`Common professional methods may include ${list(a.methods)}. The correct combination depends on species, life stage, colony or population structure, building type, infestation extent, occupant sensitivity, product labels, local rules, and whether the source is inside, outside, or in an adjoining property. More treatment is not automatically better; accurate placement and source correction usually matter more than broad application.`,`Request an explanation of how each proposed method affects the pest. Baits depend on feeding and transfer. Traps depend on placement, behavior, and sufficient numbers. Residual products depend on legal application sites and contact. Heat depends on achieving and holding lethal temperatures in difficult locations. Exclusion depends on confirming that animals or active colonies will not be trapped inside. Monitoring depends on correct device placement and consistent interpretation.`]},
  {heading:'Safety, preparation, and communication',paragraphs:[`Tell the provider about children, pregnancy, pets, aquariums, respiratory conditions, allergies, food preparation, medical equipment, organic-certification requirements, tenants, employees, and any other sensitive condition. Ask for written preparation and re-entry instructions tied to the actual products or methods. Do not rely on generic statements such as “safe when dry” without understanding the label and the treatment area.`,`Preparation should be proportionate. Excessive clearing can spread pests, remove evidence, expose occupants, or create unnecessary labor. Inadequate preparation can block access and reduce effectiveness. Confirm which items must be moved, bagged, laundered, discarded, covered, disconnected, or left untouched; who is responsible; and what happens if the provider cannot access a required area.`]},
  {heading:'How to compare quotes and provider claims',paragraphs:[`Compare the diagnosis and scope before comparing price. A lower estimate may exclude follow-up, exterior work, inaccessible areas, cleanup, repairs, monitoring devices, warranty service, or treatment of related units. A higher estimate is not automatically superior either. The written proposal should connect each charge to an inspection finding and a defined task.`,`Verify the legal business name, license or certification required by the state, insurance, contact details, complaint history where available, product information, service schedule, cancellation terms, warranty conditions, and who will actually perform the work. Avoid pressure to authorize immediate broad treatment when the pest has not been identified or the scope is not documented.`]},
  {heading:'What to expect after service',paragraphs:[`Post-service expectations depend on biology and method. Some visible pests may decline quickly, while eggs, pupae, hidden colonies, bait uptake, trap response, or animals outside the structure may require time. Ask what level of activity is expected during the first day, week, and month; what evidence indicates progress; and what evidence requires a callback.`,`Keep a simple activity log. Record dates, rooms, trap counts, bites, sounds, droppings, damage, weather, sanitation changes, repairs, and photographs. Do not move monitoring devices or add unapproved sprays because that can disrupt the treatment and make the results harder to interpret. Complete the agreed repairs and sanitation actions within the recommended sequence.`]},
  {heading:'Long-term prevention priorities',paragraphs:[`Useful preventive actions include ${list(a.prevention)}. Prevention is strongest when it is specific to the pest and verified through inspection. Sealing every visible crack while leaving a major utility opening, roof defect, drain pathway, or food source unchanged wastes effort. Likewise, sanitation alone will not stop pests that are nesting in structural voids or entering through damaged building components.`,`Create a maintenance routine covering moisture, drainage, waste, food storage, vegetation, screens, door sweeps, roof edges, vents, utility penetrations, stored goods, pet areas, and seasonal inspection. Property managers should assign responsibility and deadlines rather than leaving recommendations as general notes. Reinspect corrected areas to confirm that the condition was actually resolved.`]},
  {heading:'When the situation is urgent',paragraphs:[`Urgent evaluation is appropriate when there is a known severe allergy, aggressive stinging activity, an animal trapped in an occupied area, contamination of food or medical environments, extensive electrical gnawing, structural damage, sewage involvement, rapidly spreading activity, or exposure involving an infant, medically vulnerable person, or pet. Keep people away from the affected zone and avoid actions that provoke the pest.`,`For suspected poisoning, bites, stings, or illness, contact the appropriate medical, veterinary, poison-control, or emergency service. Pest-control information is not medical advice. A pest provider can address the source and treatment area, but health symptoms require assessment by a qualified health professional.`]},
  {heading:'Final hiring checklist',paragraphs:[`Before authorizing work, confirm the pest identification, evidence, affected areas, proposed methods, products, preparation, safety instructions, re-entry time, number of visits, monitoring, repairs, exclusions, total price, payment schedule, warranty, and follow-up trigger. Keep copies of the inspection report, agreement, labels or product names, invoices, and service records.`,`The best outcome is not simply fewer visible pests after one visit. It is a documented reduction in activity, correction of the conditions supporting the problem, protected occupants and property, and a clear plan for monitoring recurrence. Use this guide to organize the questions, then rely on an inspection of the actual property for the final decision.`]},
 ];
}

export function articleFaqs(a:Article){return [
 [`What is the first step when I suspect ${a.pest}?`,`Document the signs and request accurate identification before applying broad treatment or disturbing likely harborages.`],
 [`Can I handle ${a.pest} myself?`,`Minor isolated activity may sometimes be addressed with sanitation, exclusion, or labeled consumer products, but recurring, hidden, damaging, contaminating, or uncertain activity warrants professional inspection.`],
 ['How many visits will be required?','The number of visits depends on pest biology, infestation extent, treatment method, building conditions, monitoring results, and whether neighboring or exterior sources remain active.'],
 ['What should I get in writing?','Request inspection findings, target pest, scope, products or methods, preparation, safety instructions, visits, exclusions, total price, warranty, and follow-up.'],
 ['How can I prevent recurrence?',`Prioritize ${list(a.prevention)} and verify that the original source and entry conditions have been corrected.`],
 ];}
