export const SITE = {
  name: 'Batys Pest Control',
  domain: 'batyspestcontrol.com',
  url: 'https://batyspestcontrol.com',
  phoneDisplay: '(614) 926-0787',
  phoneHref: 'tel:+16149260787',
  description:
    'Pest-control information and independent local provider referrals across the United States.',
} as const;

export const HIGH_VALUE_SERVICE_SLUGS = new Set([
  'general-pest-control',
  'residential-pest-control',
  'commercial-pest-control',
  'pest-inspection',
  'ant-control',
  'cockroach-control',
  'bed-bug-treatment',
  'termite-control',
  'termite-inspection',
  'termite-treatment',
  'rodent-control',
  'mouse-control',
  'rat-control',
  'mosquito-control',
  'spider-control',
]);

export const PRIORITY_CITY_KEYS = new Set([
  'az/phoenix', 'az/tucson',
  'ca/los-angeles', 'ca/san-diego', 'ca/san-francisco', 'ca/san-jose', 'ca/sacramento', 'ca/fresno',
  'co/denver', 'co/colorado-springs',
  'dc/washington',
  'fl/jacksonville', 'fl/miami', 'fl/tampa', 'fl/orlando', 'fl/saint-petersburg',
  'ga/atlanta', 'ga/augusta',
  'hi/honolulu',
  'il/chicago', 'il/aurora',
  'in/indianapolis',
  'la/new-orleans', 'la/baton-rouge',
  'ma/boston', 'ma/worcester',
  'md/baltimore',
  'mi/detroit', 'mi/grand-rapids',
  'mn/minneapolis', 'mn/saint-paul',
  'mo/kansas-city', 'mo/saint-louis',
  'nc/charlotte', 'nc/raleigh', 'nc/greensboro',
  'ne/omaha',
  'nj/newark', 'nj/jersey-city',
  'nm/albuquerque',
  'nv/las-vegas', 'nv/henderson',
  'ny/new-york', 'ny/buffalo', 'ny/rochester',
  'oh/columbus', 'oh/cleveland', 'oh/cincinnati',
  'ok/oklahoma-city', 'ok/tulsa',
  'or/portland',
  'pa/philadelphia', 'pa/pittsburgh',
  'sc/charleston', 'sc/columbia',
  'tn/nashville', 'tn/memphis', 'tn/knoxville',
  'tx/houston', 'tx/san-antonio', 'tx/dallas', 'tx/austin', 'tx/fort-worth', 'tx/el-paso',
  'ut/salt-lake-city',
  'va/virginia-beach', 'va/richmond',
  'wa/seattle', 'wa/spokane', 'wa/tacoma',
  'wi/milwaukee', 'wi/madison',
]);
