import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { findService, pestServices } from '@/lib/locations';
import { SITE } from '@/lib/site';

type Props = { params: Promise<{ service: string }> };

export function generateStaticParams() { return pestServices.map((service) => ({ service: service.slug })); }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { service: serviceSlug } = await params;
  const service = findService(serviceSlug);
  if (!service) return {};
  return { title: service.name, description: service.description, alternates: { canonical: `/services/${service.slug}` } };
}

const faqs = [
  ['When should I request a professional inspection?', 'Request an inspection when activity is recurring, identification is uncertain, damage or contamination is possible, nests or entry points are difficult to reach, or do-it-yourself measures have not resolved the source.'],
  ['What should a written quote include?', 'It should identify the target pest, treatment areas, products or methods, preparation steps, number of visits, exclusions, follow-up, warranty terms, and total price.'],
  ['Are pest-control requirements the same in every state?', 'No. Licensing, certification, notification, recordkeeping, and product-use requirements vary. Confirm the provider’s current credentials and the rules that apply in your state.'],
  ['How should I prepare for treatment?', 'Preparation depends on the pest and method. Follow only the written instructions supplied by the provider, especially for food storage, pets, children, linens, furniture, ventilation, and re-entry times.'],
];

export default async function ServicePage({ params }: Props) {
  const { service: serviceSlug } = await params;
  const service = findService(serviceSlug);
  if (!service) notFound();
  const related = pestServices.filter((item) => item.category === service.category && item.slug !== service.slug).slice(0, 6);
  const schema = { '@context':'https://schema.org','@type':'Service',name:service.name,description:service.description,provider:{'@type':'Organization',name:SITE.name,url:SITE.url},areaServed:{'@type':'Country',name:'United States'} };
  const faqSchema = { '@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}})) };

  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}} />
    <section className="bg-[#092e27] px-4 py-20 text-white"><div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-[1.15fr_.85fr]"><div><nav className="text-sm text-emerald-100/70"><Link href="/">Home</Link><span className="mx-2">/</span><Link href="/services">Services</Link><span className="mx-2">/</span>{service.name}</nav><p className="mt-10 text-xs font-black uppercase tracking-[.2em] text-emerald-300">{service.category}</p><h1 className="mt-4 font-heading text-5xl font-black leading-tight sm:text-6xl">{service.name}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-emerald-50/80">{service.description}</p><div className="mt-8 flex flex-wrap gap-4"><a href={SITE.phoneHref} className="rounded-lg bg-emerald-500 px-6 py-4 font-black">Call {SITE.phoneDisplay}</a><Link href="/locations" className="rounded-lg border border-white/25 bg-white/10 px-6 py-4 font-black">Find Your Location</Link></div><div className="mt-8 flex flex-wrap gap-5 text-sm font-bold text-emerald-50/85">{['Inspection-first approach','Independent local providers','Written scope recommended'].map(x=><span key={x}>✓ {x}</span>)}</div></div><aside className="rounded-2xl bg-white p-7 text-[#10233b] shadow-2xl"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Request availability</p><h2 className="mt-2 font-heading text-2xl font-black">Describe the pest problem</h2><div className="mt-5 grid gap-3">{['City or ZIP code','Pest seen or suspected','Indoor or outdoor activity','How long it has been present'].map(x=><div key={x} className="rounded-lg border border-slate-200 px-4 py-3 text-sm text-slate-500">{x}</div>)}</div><a href={SITE.phoneHref} className="mt-4 block rounded-lg bg-emerald-500 px-5 py-4 text-center font-black text-white">Call for Service</a><p className="mt-3 text-center text-xs text-slate-500">Coverage and response time must be confirmed by phone.</p></aside></div></section>

    <section className="border-b border-slate-200 bg-white px-4"><div className="mx-auto grid max-w-7xl grid-cols-2 md:grid-cols-4">{[['01','Identify'],['02','Inspect'],['03','Treat'],['04','Prevent']].map(([n,t])=><div key={t} className="border-r border-slate-200 p-6 text-center last:border-r-0"><strong className="text-emerald-700">{n}</strong><p className="mt-1 font-black text-[#10233b]">{t}</p></div>)}</div></section>

    <section className="px-4 py-20"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1fr_340px]"><article className="max-w-none"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Service overview</p><h2 className="mt-3 font-heading text-4xl font-black text-[#10233b]">What professional {service.name.toLowerCase()} should address</h2><p className="mt-5 text-lg leading-8 text-slate-600">A sound service begins with identification. Similar-looking insects, rodents, damage patterns, droppings, bites, odors, and nesting materials can point to different causes. The inspection should determine the target pest, the extent of activity, contributing moisture or sanitation conditions, access points, harborage, and the areas that require treatment or exclusion.</p><p className="mt-5 leading-8 text-slate-600">The provider should explain why the proposed method fits the inspection findings. Depending on the pest, this may involve targeted application, baiting, trapping, heat, vacuuming, physical removal, sanitation correction, moisture control, sealing, screening, structural repair, monitoring, or scheduled follow-up. A broad treatment without clear identification is a weak plan.</p>
      <h2 className="mt-12 font-heading text-3xl font-black text-[#10233b]">Signs that justify an inspection</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{['Repeated sightings or activity','Droppings, shed skins, eggs, or nesting material','Bites, stings, odors, noises, or contamination','Wood, wiring, insulation, food, fabric, or landscape damage','Visible entry gaps, moisture, or harborage','Activity returning after DIY treatment'].map(x=><div key={x} className="rounded-xl bg-slate-50 p-5 font-bold text-slate-700"><span className="mr-2 text-emerald-600">✓</span>{x}</div>)}</div>
      <h2 className="mt-12 font-heading text-3xl font-black text-[#10233b]">What to confirm before work begins</h2><ol className="mt-6 space-y-5">{[['Pest identification','Ask what evidence supports the identification and whether another pest could produce similar signs.'],['Treatment scope','Confirm exactly which rooms, structures, exterior zones, voids, entry points, or nesting areas are included.'],['Products and methods','Request product labels or method details, preparation requirements, re-entry instructions, and precautions for people, pets, food, and sensitive environments.'],['Price and follow-up','Get the total price, number of visits, monitoring plan, exclusions, warranty limits, and conditions that could create additional charges in writing.']].map(([h,p],i)=><li key={h} className="flex gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-emerald-100 font-black text-emerald-800">{i+1}</span><div><h3 className="font-heading text-xl font-black text-[#10233b]">{h}</h3><p className="mt-1 leading-7 text-slate-600">{p}</p></div></li>)}</ol>
      <h2 className="mt-12 font-heading text-3xl font-black text-[#10233b]">After treatment and prevention</h2><p className="mt-5 leading-8 text-slate-600">Results should be measured against the target pest’s biology and the treatment plan. Some services can produce rapid reduction, while colonies, eggs, hidden harborages, seasonal pressure, or structural entry points may require monitoring and repeat visits. Follow the provider’s written cleanup, ventilation, re-entry, sanitation, repair, storage, landscaping, and exclusion instructions.</p><p className="mt-5 leading-8 text-slate-600">Long-term control usually depends on removing the conditions that supported activity. That can include repairing leaks, reducing humidity, storing food and pet feed in sealed containers, managing waste, trimming vegetation, removing clutter, sealing penetrations, repairing screens, correcting drainage, and documenting new signs between visits.</p></article>
      <aside><div className="sticky top-24 rounded-2xl border border-slate-200 bg-slate-50 p-6"><h2 className="font-heading text-2xl font-black text-[#10233b]">Related services</h2><div className="mt-5 grid gap-3">{related.map(item=><Link key={item.slug} href={`/services/${item.slug}`} className="rounded-lg bg-white p-4 text-sm font-bold text-slate-700 shadow-sm hover:text-emerald-700">{item.name} →</Link>)}</div><Link href="/services" className="mt-5 inline-flex font-black text-emerald-700">View all services →</Link></div></aside></div></section>

    <section className="bg-slate-50 px-4 py-20"><div className="mx-auto max-w-4xl text-center"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Frequently asked questions</p><h2 className="mt-3 font-heading text-4xl font-black text-[#10233b]">Questions about {service.name.toLowerCase()}</h2><div className="mt-10 space-y-3 text-left">{faqs.map(([q,a])=><details key={q} className="rounded-xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer font-black text-[#10233b]">{q}</summary><p className="mt-3 leading-7 text-slate-600">{a}</p></details>)}</div></div></section>

    <section className="bg-emerald-500 px-4 py-14 text-white"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 md:flex-row md:items-center"><div><h2 className="font-heading text-3xl font-black">Need {service.name.toLowerCase()} information for your area?</h2><p className="mt-2 text-emerald-50">Choose your location or call to check provider availability.</p></div><a href={SITE.phoneHref} className="rounded-lg bg-white px-7 py-4 font-black text-[#10233b]">Call {SITE.phoneDisplay}</a></div></section>
  </>;
}