import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { articleFaqs, articleSections, articles, findArticle } from '@/lib/articles';
import { findService } from '@/lib/locations';
import { SITE } from '@/lib/site';

type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return articles.map(a=>({slug:a.slug}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const a=findArticle(slug);if(!a)return{};return{title:a.title,description:a.summary,alternates:{canonical:`/articles/${a.slug}`},openGraph:{title:a.title,description:a.summary,type:'article'}}}

export default async function ArticlePage({params}:Props){
 const {slug}=await params; const a=findArticle(slug); if(!a)notFound();
 const sections=articleSections(a); const faqs=articleFaqs(a); const service=findService(a.serviceSlug);
 const related=articles.filter(x=>x.slug!==a.slug&&(x.category===a.category||x.serviceSlug===a.serviceSlug)).slice(0,4);
 const articleSchema={'@context':'https://schema.org','@type':'Article',headline:a.title,description:a.summary,author:{'@type':'Organization',name:SITE.name},publisher:{'@type':'Organization',name:SITE.name},mainEntityOfPage:`${SITE.url}/articles/${a.slug}`};
 const faqSchema={'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(([q,ans])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:ans}}))};
 const crumbSchema={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:SITE.url},{'@type':'ListItem',position:2,name:'Articles',item:`${SITE.url}/articles`},{'@type':'ListItem',position:3,name:a.title,item:`${SITE.url}/articles/${a.slug}`}]};
 return <>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleSchema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(crumbSchema)}}/>
  <section className="bg-[#092e27] px-4 py-20 text-white"><div className="mx-auto max-w-5xl"><nav className="text-sm text-emerald-100/70"><Link href="/">Home</Link><span className="mx-2">/</span><Link href="/articles">Articles</Link><span className="mx-2">/</span>{a.category}</nav><p className="mt-10 text-xs font-black uppercase tracking-[.2em] text-emerald-300">{a.category} Guide</p><h1 className="mt-4 font-heading text-5xl font-black leading-tight sm:text-6xl">{a.title}</h1><p className="mt-6 max-w-4xl text-lg leading-8 text-emerald-50/80">{a.summary}</p><div className="mt-7 flex flex-wrap gap-5 text-sm font-bold text-emerald-50/85"><span>Reviewed for search intent</span><span>•</span><span>Long-form property guide</span><span>•</span><span>Independent-provider disclosure</span></div></div></section>

  <div className="mx-auto grid max-w-7xl gap-12 px-4 py-16 lg:grid-cols-[1fr_320px]"><article className="min-w-0"><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><p className="font-black text-emerald-950">Key takeaway</p><p className="mt-2 leading-7 text-emerald-950/80">Accurate identification and inspection come before treatment. Use the signs and methods below to organize questions, then rely on a property-specific assessment before authorizing work.</p></div>{sections.map((s,i)=><section key={s.heading} className="mt-12"><h2 className="font-heading text-3xl font-black leading-tight text-[#10233b]">{s.heading}</h2>{s.paragraphs.map((p,j)=><p key={j} className="mt-5 text-[17px] leading-8 text-slate-700">{p}</p>)}{i===1&&<div className="mt-7 grid gap-3 sm:grid-cols-2">{a.signs.map(x=><div key={x} className="rounded-xl bg-slate-50 p-4 font-bold text-slate-700"><span className="mr-2 text-emerald-600">✓</span>{x}</div>)}</div>}{i===4&&<div className="mt-7 grid gap-3 sm:grid-cols-2">{a.methods.map(x=><div key={x} className="rounded-xl border border-slate-200 p-4 font-bold text-slate-700">{x}</div>)}</div>}</section>)}
   <section className="mt-14 border-t border-slate-200 pt-12"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Frequently asked questions</p><h2 className="mt-3 font-heading text-4xl font-black text-[#10233b]">Questions about {a.pest}</h2><div className="mt-8 space-y-3">{faqs.map(([q,ans])=><details key={q} className="rounded-xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer font-black text-[#10233b]">{q}</summary><p className="mt-3 leading-7 text-slate-600">{ans}</p></details>)}</div></section>
  </article><aside><div className="sticky top-24 space-y-6"><div className="rounded-2xl bg-[#0b263e] p-6 text-white"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-300">Need local information?</p><h2 className="mt-3 font-heading text-2xl font-black">Check provider availability</h2><p className="mt-3 text-sm leading-6 text-slate-300">Describe the location, pest evidence, affected areas, and urgency.</p><a href={SITE.phoneHref} className="mt-5 block rounded-lg bg-emerald-500 px-5 py-4 text-center font-black">Call {SITE.phoneDisplay}</a></div>{service&&<div className="rounded-2xl border border-slate-200 bg-slate-50 p-6"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Related service</p><h2 className="mt-3 font-heading text-2xl font-black text-[#10233b]">{service.name}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{service.description}</p><Link href={`/services/${service.slug}`} className="mt-5 inline-flex font-black text-emerald-700">View service →</Link></div>}<div className="rounded-2xl border border-slate-200 p-6"><h2 className="font-heading text-2xl font-black text-[#10233b]">Related guides</h2><div className="mt-5 space-y-4">{related.map(x=><Link key={x.slug} href={`/articles/${x.slug}`} className="block border-b border-slate-100 pb-4 text-sm font-bold leading-6 text-slate-700 last:border-0">{x.title} →</Link>)}</div></div></div></aside></div>
  <section className="bg-emerald-500 px-4 py-14 text-white"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 md:flex-row md:items-center"><div><h2 className="font-heading text-3xl font-black">Need help choosing the next step?</h2><p className="mt-2 text-emerald-50">Browse services and locations or call to check independent-provider availability.</p></div><div className="flex gap-3"><Link href="/services" className="rounded-lg bg-[#10233b] px-6 py-4 font-black">View Services</Link><a href={SITE.phoneHref} className="rounded-lg bg-white px-6 py-4 font-black text-[#10233b]">Call Now</a></div></div></section>
 </>;
}
